# Generated by Django 6.0 on 2025-12-18 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_audio', models.FileField(upload_to='audio/original/')),
                ('noisy_audio', models.FileField(blank=True, null=True, upload_to='audio/noisy/')),
                ('enhanced_audio', models.FileField(blank=True, null=True, upload_to='audio/enhanced/')),
                ('noisy_spectrogram', models.ImageField(blank=True, null=True, upload_to='spectrograms/noisy/')),
                ('enhanced_spectrogram', models.ImageField(blank=True, null=True, upload_to='spectrograms/enhanced/')),
                ('noise_type', models.CharField(default='None', max_length=50)),
                ('snr', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
