# Generated by Django 6.0 on 2025-12-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioprocessing',
            name='enhanced_audio',
        ),
        migrations.AddField(
            model_name='audioprocessing',
            name='processed_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/processed/'),
        ),
        migrations.AddField(
            model_name='audioprocessing',
            name='processing_type',
            field=models.CharField(choices=[('noise_reduction', 'Noise Reduction'), ('volume_boost', 'Volume Boost')], default='noise_reduction', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audioprocessing',
            name='noise_type',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='audioprocessing',
            name='snr',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
