# Generated by Django 6.0 on 2025-12-24 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0002_remove_audioprocessing_enhanced_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseReduceV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to='v2/input/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='v2/output/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
