# Generated by Django 6.0 on 2025-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0003_noisereducev2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisereducev2',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noisereducev2',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
