# Generated by Django 6.0 on 2025-12-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0004_noisereducev2_error_message_noisereducev2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisereducev2',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
