# Generated by Django 6.0 on 2025-12-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0005_noisereducev2_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoiseReduceV2',
        ),
    ]
