# Generated by Django 6.0 on 2025-12-24 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_api', '0006_delete_noisereducev2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioprocessing',
            name='enhanced_spectrogram',
        ),
        migrations.RemoveField(
            model_name='audioprocessing',
            name='noise_type',
        ),
        migrations.RemoveField(
            model_name='audioprocessing',
            name='noisy_audio',
        ),
        migrations.RemoveField(
            model_name='audioprocessing',
            name='noisy_spectrogram',
        ),
        migrations.RemoveField(
            model_name='audioprocessing',
            name='snr',
        ),
        migrations.AddField(
            model_name='audioprocessing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
